In [3]:
import pandas as pd

In [4]:
t = pd.read_csv("customer_sales_messy.csv")

In [5]:
t

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [6]:
t.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [7]:
t.isnull().sum().sum()

np.int64(10)

In [8]:
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         53 non-null     int64
 1   Customer_Name    52 non-null     object
 2   City             51 non-null     object
 3   Product          53 non-null     object
 4   Category         52 non-null     object
 5   Quantity         53 non-null     int64
 6   Price            51 non-null     float64
 7   Order_Date       52 non-null     object
 8   Payment_Mode     52 non-null     object
 9   Salesperson      53 non-null     object
 10  Customer_Rating  51 non-null     float64
dtypes: float64(2), int64(2), object(7)
memory usage: 4.7+ KB

In [9]:
t.shape

(53, 11)

In [10]:
t.describe()

          Order_ID   Quantity         Price  Customer_Rating
count    53.000000  53.000000     51.000000        51.000000
mean   1024.584906   1.471698  10737.254902         4.196078
std      14.692272   0.696247  16851.970221         0.693386
min    1001.000000   1.000000    780.000000         3.000000
25%    1012.000000   1.000000   1975.000000         4.000000
50%    1024.000000   1.000000   3250.000000         4.000000
75%    1037.000000   2.000000   8350.000000         5.000000
max    1050.000000   4.000000  57000.000000         5.000000

In [11]:
t.duplicated().sum()

np.int64(2)

In [12]:
t.drop_duplicates()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [13]:
t.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Product', 'Category', 'Quantity',
       'Price', 'Order_Date', 'Payment_Mode', 'Salesperson',
       'Customer_Rating'],
      dtype='object')

In [14]:
t[t.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [15]:
m = t.isnull().sum()

In [16]:
m

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [17]:
t["Customer_Name"] = t["Customer_Name"].fillna("Unknown")

In [18]:
t.isnull().sum()

Order_ID           0
Customer_Name      0
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [19]:
t[t.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [20]:
t["Price"] =t["Price"].fillna(t["Price"].min())

In [21]:
t

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [22]:
t[t.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [23]:
t=t.dropna()

In [24]:
t[t.isnull().any(axis=1)]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Price, Order_Date, Payment_Mode, Salesperson, Customer_Rating]
Index: []

In [25]:
t

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [26]:
f = pd.read_csv("customer_sales_messy.csv")

In [27]:
f.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [28]:
f_new = f.dropna(subset=["Customer_Name"])

In [29]:
f_new.isnull().sum()

Order_ID           0
Customer_Name      0
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [30]:
f["Order_ID"]

0     1001
1     1002
2     1003
3     1004
4     1005
5     1006
6     1007
7     1008
8     1009
9     1010
10    1011
11    1012
12    1013
13    1014
14    1015
15    1016
16    1017
17    1018
18    1019
19    1020
20    1021
21    1022
22    1023
23    1024
24    1025
25    1026
26    1027
27    1028
28    1029
29    1030
30    1031
31    1032
32    1033
33    1034
34    1035
35    1036
36    1037
37    1038
38    1039
39    1040
40    1041
41    1042
42    1043
43    1044
44    1045
45    1046
46    1047
47    1048
48    1049
49    1050
50    1003
51    1015
52    1010
Name: Order_ID, dtype: int64

In [31]:
f[f.duplicated()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0

In [32]:
f[f["Order_ID"].duplicated()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [33]:
f

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [34]:
f[f["Order_ID"]==1010]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [35]:
t["City"].str.upper()

0       CHENNAI
1       CHENNAI
2       CHENNAI
3     BANGALORE
4     BENGALURU
5     HYDERABAD
6     HYDERABAD
7        MUMBAI
8        MUMBAI
9          PUNE
10         PUNE
12      CHENNAI
13        KOCHI
14        KOCHI
15      CHENNAI
17        DELHI
18    HYDERABAD
19       MUMBAI
20      CHENNAI
22    BENGALURU
23    HYDERABAD
24         PUNE
25        DELHI
26      KOLKATA
27      KOLKATA
29      CHENNAI
30      CHENNAI
31    HYDERABAD
32       MUMBAI
33       MUMBAI
35        DELHI
36      KOLKATA
37      KOLKATA
38        KOCHI
39      CHENNAI
40    BANGALORE
41    HYDERABAD
42        DELHI
43      CHENNAI
44      CHENNAI
46         PUNE
48        KOCHI
49    BENGALURU
50      CHENNAI
51        KOCHI
52         PUNE
Name: City, dtype: object

In [36]:
f_new["City"] = f_new["City"].str.upper()

/tmp/ipykernel_1416/2482477327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_new["City"] = f_new["City"].str.upper()

In [37]:
f_new

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,CHENNAI,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,CHENNAI,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,BANGALORE,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,BENGALURU,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,MUMBAI,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,MUMBAI,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,PUNE,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,PUNE,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,CHENNAI,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,KOCHI,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,CHENNAI,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,DELHI,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,DELHI,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,HYDERABAD,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,MUMBAI,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,CHENNAI,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,BANGALORE,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,BENGALURU,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,HYDERABAD,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,PUNE,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,DELHI,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,KOLKATA,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,KOLKATA,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,KOCHI,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,CHENNAI,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,CHENNAI,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,HYDERABAD,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,MUMBAI,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,MUMBAI,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,PUNE,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,DELHI,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,KOLKATA,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,KOLKATA,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,KOCHI,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,CHENNAI,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,BANGALORE,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,HYDERABAD,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,DELHI,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,CHENNAI,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,PUNE,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,PUNE,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,KOCHI,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,BENGALURU,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,PUNE,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [38]:
f_new["City"].unique()

array(['CHENNAI', ' CHENNAI', 'BANGALORE', 'BENGALURU', 'HYDERABAD',
       'MUMBAI', 'PUNE', nan, 'KOCHI', 'DELHI', 'KOLKATA'], dtype=object)

In [39]:
f_new["City"] = f_new["City"].str.strip()

/tmp/ipykernel_1416/358626157.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_new["City"] = f_new["City"].str.strip()

In [40]:
f_new["City"].unique()

array(['CHENNAI', 'BANGALORE', 'BENGALURU', 'HYDERABAD', 'MUMBAI', 'PUNE',
       nan, 'KOCHI', 'DELHI', 'KOLKATA'], dtype=object)

In [41]:
f_new["City"].nunique()

9

In [42]:
f_new

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,CHENNAI,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,CHENNAI,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,BANGALORE,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,BENGALURU,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,MUMBAI,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,MUMBAI,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,PUNE,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,PUNE,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,CHENNAI,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,KOCHI,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,CHENNAI,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,DELHI,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,DELHI,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,HYDERABAD,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,MUMBAI,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,CHENNAI,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,BANGALORE,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,BENGALURU,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,HYDERABAD,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,PUNE,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,DELHI,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,KOLKATA,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,KOLKATA,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,KOCHI,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,CHENNAI,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,CHENNAI,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,HYDERABAD,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,MUMBAI,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,MUMBAI,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,PUNE,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,DELHI,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,KOLKATA,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,KOLKATA,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,KOCHI,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,CHENNAI,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,BANGALORE,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,HYDERABAD,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,DELHI,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,CHENNAI,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,PUNE,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,PUNE,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,KOCHI,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,BENGALURU,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,PUNE,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [44]:
f_new["Payment_Mode"].unique()

array([' cash ', 'UPI', 'upi', 'Card', 'CARD ', 'cash', 'Cash', 'card',
       nan, ' Cash', 'CARD'], dtype=object)

In [45]:
t["Payment_Mode"].unique()

array([' cash ', 'UPI', 'upi', 'Card', 'CARD ', 'Cash', 'cash', 'card',
       ' Cash', 'CARD'], dtype=object)

In [46]:
t["Payment_Mode"]=t["Payment_Mode"].str.strip()

/tmp/ipykernel_1416/4213236604.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Payment_Mode"]=t["Payment_Mode"].str.strip()

In [47]:
t["Payment_Mode"].unique()

array(['cash', 'UPI', 'upi', 'Card', 'CARD', 'Cash', 'card'], dtype=object)

In [48]:
t["Payment_Mode"]=t["Payment_Mode"].str.title()

/tmp/ipykernel_1416/2498528561.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Payment_Mode"]=t["Payment_Mode"].str.title()

In [49]:
t["Payment_Mode"].unique()

array(['Cash', 'Upi', 'Card'], dtype=object)

In [50]:
t

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,Cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,Upi,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,Upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,Cash,Meena,5.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,Upi,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,Upi,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,Upi,Meena,5.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,Upi,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,Cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,Upi,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,Card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,Upi,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,Upi,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,Upi,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,Card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,22/09/2026,Upi,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,Cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,Upi,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,Card,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,Upi,Meena,5.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,Upi,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [51]:
t.head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [53]:
t["Customer_Name"] = (t["Customer_Name"].str.strip().str.title())
t["City"] = (t["City"].str.strip().str.title())
t.head()

/tmp/ipykernel_1416/133825337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Customer_Name"] = (t["Customer_Name"].str.strip().str.title())
/tmp/ipykernel_1416/133825337.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["City"] = (t["City"].str.strip().str.title())

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [54]:
t["City"]=t["City"].replace("Bengaluru","Bangalore")
t.head()

/tmp/ipykernel_1416/3156815800.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["City"]=t["City"].replace("Bengaluru","Bangalore")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [60]:
t["Order_Date"].dtype

dtype('O')

In [61]:
t["Order_Date"] = pd.to_datetime(t["Order_Date"],errors="coerce")
t.head()

/tmp/ipykernel_1416/2604681681.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Order_Date"] = pd.to_datetime(t["Order_Date"],errors="coerce")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,NaT,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,NaT,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [62]:
t["Order_Date"].isnull().sum()

np.int64(25)

In [63]:
t

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,NaT,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,NaT,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,NaT,Cash,Ravi,4.0
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.0,2026-09-05,Cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,NaT,Upi,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,Upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,Pune,Monitor,Electronics,1,11800.0,NaT,Cash,Meena,5.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,NaT,Card,Suresh,5.0
14,1015,Ramesh B,Kochi,Mouse,Electronics,3,800.0,2026-09-10,Upi,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,NaT,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,NaT,Upi,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,NaT,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,Upi,Meena,5.0
22,1023,Keerthi M,Bangalore,Keyboard,Electronics,1,1900.0,2026-09-14,Upi,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,NaT,Cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,NaT,Upi,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,NaT,Card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,NaT,Cash,Meena,4.0
30,1031,Sowmya R,Chennai,Office Chair,Furniture,2,6300.0,2026-09-18,Upi,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,NaT,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,NaT,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,NaT,Upi,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,NaT,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,Upi,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,NaT,Card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,NaT,Upi,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,NaT,Cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,Upi,Ravi,5.0
43,1044,Rahul Verma,Chennai,Laptop,Electronics,1,55500.0,NaT,Card,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,Upi,Meena,5.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,NaT,Card,Suresh,3.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bangalore,Office Chair,Furniture,1,6600.0,NaT,Card,Suresh,5.0
50,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0
51,1015,Ramesh B,Kochi,Mouse,Electronics,3,800.0,2026-09-10,Upi,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [66]:
t["Order_Date"] = t["Order_Date"].fillna("2026-01-01")
t.head(10)

/tmp/ipykernel_1416/3538504195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Order_Date"] = t["Order_Date"].fillna("2026-01-01")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,2026-01-01,Cash,Ravi,4.0
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.0,2026-09-05,Cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,2026-01-01,Upi,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,Upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [64]:
t[t["Order_Date"].isnull()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,NaT,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,NaT,Card,Suresh,3.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,NaT,Cash,Ravi,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,NaT,Upi,Meena,5.0
10,1011,Rohit Das,Pune,Monitor,Electronics,1,11800.0,NaT,Cash,Meena,5.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,NaT,Card,Suresh,5.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,NaT,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,NaT,Upi,Meena,5.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,NaT,Card,Suresh,3.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,NaT,Cash,Meena,5.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,NaT,Upi,Suresh,3.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,NaT,Card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,NaT,Cash,Meena,4.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,NaT,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,NaT,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,NaT,Upi,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,NaT,Cash,Meena,4.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,NaT,Card,Suresh,4.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,NaT,Upi,Ravi,4.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,NaT,Cash,Meena,4.0
43,1044,Rahul Verma,Chennai,Laptop,Electronics,1,55500.0,NaT,Card,Suresh,4.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,NaT,Card,Suresh,3.0
49,1050,Vikram J,Bangalore,Office Chair,Furniture,1,6600.0,NaT,Card,Suresh,5.0
50,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0

In [68]:
t["Order_Date"].dt.month

0     9
1     1
2     1
3     1
4     9
5     1
6     9
7     1
8     9
9     9
10    1
12    9
13    1
14    9
15    1
17    1
18    9
19    1
20    9
22    9
23    1
24    9
25    1
26    9
27    1
29    1
30    9
31    1
32    1
33    1
35    1
36    9
37    1
38    9
39    1
40    9
41    1
42    9
43    1
44    9
46    1
48    9
49    1
50    1
51    9
52    9
Name: Order_Date, dtype: int32

In [69]:
t.describe()

,Order_ID,Quantity,Price,Order_Date,Customer_Rating
count,46.000000,46.000000,46.000000,46,46.000000
mean,1023.782609,1.521739,11015.434783,2026-04-27 13:33:54.782608640,4.152174
min,1001.000000,1.000000,780.000000,2026-01-01 00:00:00,3.000000
25%,1010.250000,1.000000,1800.000000,2026-01-01 00:00:00,4.000000
50%,1023.500000,1.000000,3175.000000,2026-01-01 00:00:00,4.000000
75%,1036.750000,2.000000,8375.000000,2026-09-11 12:00:00,5.000000
max,1050.000000,4.000000,57000.000000,2026-09-27 00:00:00,5.000000
std,14.785748,0.722315,17741.238302,NaN,0.698169

In [70]:
t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, 0 to 52
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         46 non-null     int64
 1   Customer_Name    46 non-null     object
 2   City             46 non-null     object
 3   Product          46 non-null     object
 4   Category         46 non-null     object
 5   Quantity         46 non-null     int64
 6   Price            46 non-null     float64
 7   Order_Date       46 non-null     datetime64[ns]
 8   Payment_Mode     46 non-null     object
 9   Salesperson      46 non-null     object
 10  Customer_Rating  46 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 4.3+ KB

In [71]:
t.head(10)

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,2026-01-01,Cash,Ravi,4.0
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.0,2026-09-05,Cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,2026-01-01,Upi,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,Upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [72]:
t["Quantity"] = pd.to_numeric(t["Quantity"],errors="coerce")

/tmp/ipykernel_1416/3578888984.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Quantity"] = pd.to_numeric(t["Quantity"],errors="coerce")

In [75]:
t[t["Quantity"].isnull()]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Price, Order_Date, Payment_Mode, Salesperson, Customer_Rating]
Index: []

In [73]:
t.head(10)

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,2026-01-01,Cash,Ravi,4.0
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.0,2026-09-05,Cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,2026-01-01,Upi,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,Upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [76]:
t.dtypes

Order_ID                    int64
Customer_Name              object
City                       object
Product                    object
Category                   object
Quantity                    int64
Price                     float64
Order_Date         datetime64[ns]
Payment_Mode               object
Salesperson                object
Customer_Rating           float64
dtype: object

In [77]:
t["Total_Price"] = (t["Quantity"]*t["Price"])
t.head(10)

/tmp/ipykernel_1416/4017805701.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["Total_Price"] = (t["Quantity"]*t["Price"])

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Total_Price
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0,55000.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0,1700.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0,1800.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0,12500.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0,13000.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,2026-01-01,Cash,Ravi,4.0,8500.0
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.0,2026-09-05,Cash,Suresh,4.0,4400.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,2026-01-01,Upi,Meena,5.0,3200.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,Upi,Ravi,3.0,780.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0,3500.0

In [78]:
t[["Product","Quantity","Price","Total_Price"]]

         Product  Quantity    Price  Total_Price
0         Laptop         1  55000.0      55000.0
1          Mouse         2    850.0       1700.0
2       Keyboard         1   1800.0       1800.0
3        Monitor         1  12500.0      12500.0
4   Office Chair         2   6500.0      13000.0
5           Desk         1   8500.0       8500.0
6   Laptop Stand         2   2200.0       4400.0
7         Webcam         1   3200.0       3200.0
8     Headphones         1    780.0        780.0
9       Keyboard         2   1750.0       3500.0
10       Monitor         1  11800.0      11800.0
12        Laptop         1  55000.0      55000.0
13          Desk         1   7800.0       7800.0
14         Mouse         3    800.0       2400.0
15        Webcam         2   3100.0       6200.0
17  Laptop Stand         1   2100.0       2100.0
18        Laptop         1  56000.0      56000.0
19       Monitor         2  12000.0      24000.0
20  Office Chair         1   6400.0       6400.0
22      Keyboard         1   1900.0       1900.0
23         Mouse         4    820.0       3280.0
24        Webcam         1   3300.0       3300.0
25    Headphones         2   2750.0       5500.0
26  Laptop Stand         2   2300.0       4600.0
27        Laptop         1  54000.0      54000.0
29          Desk         1   8000.0       8000.0
30  Office Chair         2   6300.0      12600.0
31      Keyboard         1   1850.0       1850.0
32         Mouse         2    900.0       1800.0
33        Webcam         1   3150.0       3150.0
35  Laptop Stand         3   2050.0       6150.0
36       Monitor         1  12100.0      12100.0
37        Laptop         1  57000.0      57000.0
38          Desk         1   7900.0       7900.0
39         Mouse         2    780.0       1560.0
40      Keyboard         1   1800.0       1800.0
41  Office Chair         1   6100.0       6100.0
42        Webcam         2   3250.0       6500.0
43        Laptop         1  55500.0      55500.0
44       Monitor         1  12300.0      12300.0
46    Headphones         2   2850.0       5700.0
48         Mouse         2    780.0       1560.0
49  Office Chair         1   6600.0       6600.0
50      Keyboard         1   1800.0       1800.0
51         Mouse         3    800.0       2400.0
52      Keyboard         2   1750.0       3500.0

In [79]:
t.isnull().sum()

Order_ID           0
Customer_Name      0
City               0
Product            0
Category           0
Quantity           0
Price              0
Order_Date         0
Payment_Mode       0
Salesperson        0
Customer_Rating    0
Total_Price        0
dtype: int64

In [83]:
t.duplicated().sum()

np.int64(2)

In [86]:
t=t.drop_duplicates()

In [87]:
t.duplicated().sum()

np.int64(0)

In [89]:
print(t["City"].value_counts())

City
Chennai      11
Hyderabad     6
Bangalore     5
Mumbai        5
Pune          5
Kochi         4
Delhi         4
Kolkata       4
Name: count, dtype: int64

In [90]:
t["City"].value_counts()

City
Chennai      11
Hyderabad     6
Bangalore     5
Mumbai        5
Pune          5
Kochi         4
Delhi         4
Kolkata       4
Name: count, dtype: int64

In [97]:
t.groupby("Product")["Total_Price"].sum()

Product
Desk             32200.0
Headphones       11980.0
Keyboard         14350.0
Laptop          332500.0
Laptop Stand     17250.0
Monitor          72700.0
Mouse            12300.0
Office Chair     44700.0
Webcam           22350.0
Name: Total_Price, dtype: float64

In [98]:
new_table = pd.DataFrame(t.groupby("Product")["Total_Price"].sum())

In [101]:
new_table.sort_values("Total_Price",ascending=False)

              Total_Price
Product
Laptop           332500.0
Monitor           72700.0
Office Chair      44700.0
Desk              32200.0
Webcam            22350.0
Laptop Stand      17250.0
Keyboard          14350.0
Mouse             12300.0
Headphones        11980.0

In [102]:
sales_by_category = pd.DataFrame(t.groupby("Category")["Total_Price"].sum())

In [103]:
sales_by_category

             Total_Price
Category
Accessories      39600.0
Electronics     443830.0
Furniture        76900.0

In [104]:
t.groupby("Category")["Total_Price"].sum().sort_values(ascending=False)

Category
Electronics    443830.0
Furniture       76900.0
Accessories     39600.0
Name: Total_Price, dtype: float64

In [106]:
t.to_csv("Customer_Dataset_cleaned.csv",index=False)